### ISSUE TITLE
2020年以降の改正に関して

### ISSUE THREAD

**Issue by maisumakun** [masa16/holiday_japan#3]
[内閣府のサイト](http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html)を確認してみましたが、

* 体育の日は2019年限りで、2020年以降は「スポーツの日」と名前が変わります。
* 海の日を7月20日固定に戻すという案は賛否が入り乱れて流れたようで、とりあえずは2021年以降も7月第3月曜で続くようです。

以上2点に対応が必要と思われます。

**Comment by masa16** [comment]
対応しました。ありがとうございます。
